# Generated by Django 3.2.16 on 2022-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_restriction',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
