# Generated by Django 3.2.16 on 2022-11-21 04:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221120_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.movie_image_file_path),
        ),
    ]
