# Generated by Django 3.2.16 on 2022-11-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221121_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genres',
        ),
    ]
